USE UNIVER;


SELECT  AUDITORIUM_TYPE.AUDITORIUM_TYPENAME,
AVG(AUDITORIUM.AUDITORIUM_CAPACITY) [AVG], MIN(AUDITORIUM.AUDITORIUM_CAPACITY)[MIN], MAX(AUDITORIUM.AUDITORIUM_CAPACITY)[MAX],
COUNT(*)[COUNT], SUM(AUDITORIUM.AUDITORIUM_CAPACITY)[SUM]
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
GROUP BY AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
