USE UNIVER;

SELECT * FROM (
SELECT CASE 
WHEN PROGRESS.NOTE < 6 THEN '4-5'
WHEN PROGRESS.NOTE < 8 THEN '6-7'
WHEN PROGRESS.NOTE < 10 THEN '8-9'
END [MARKS], COUNT(*) [AMOUNT]

FROM PROGRESS
GROUP BY CASE 
WHEN PROGRESS.NOTE < 6 THEN '4-5'
WHEN PROGRESS.NOTE < 8 THEN '6-7'
WHEN PROGRESS.NOTE < 10 THEN '8-9'
END ) AS T
ORDER BY CASE [MARKS]
WHEN '8-9' THEN 1
WHEN '6-7' THEN 2
WHEN '4-5' THEN 3
END
