use UNIVER;

SELECT PROFESSION.PROFESSION, PROGRESS.SUBJECT, ROUND(AVG(CAST(PROGRESS.NOTE as float(4))),2) AS 'AVG'
FROM PROGRESS INNER JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
INNER JOIN PROFESSION ON GROUPS.PROFESSION = PROFESSION.PROFESSION
WHERE FACULTY.FACULTY = 'ÒÎÂ'
GROUP BY PROGRESS.SUBJECT, PROFESSION.PROFESSION
