USE UNIVER;


SELECT PROGRESS.SUBJECT, COUNT(*) AS AMOUNT, PROGRESS.NOTE
FROM PROGRESS
GROUP BY PROGRESS.SUBJECT, PROGRESS.NOTE
HAVING PROGRESS.NOTE  = '8' OR PROGRESS.NOTE = '9' 
ORDER BY PROGRESS.NOTE DESC