use UNIVER;

SELECT PULPIT.PULPIT_NAME, FACULTY.FACULTY_NAME
from	FACULTY, PULPIT 
where (FACULTY.FACULTY = PULPIT.FACULTY) and FACULTY.FACULTY IN 
(SELECT PROFESSION.FACULTY from PROFESSION 
where PROFESSION.PROFESSION_NAME LIKE '%технологии%' or PROFESSION.PROFESSION_NAME LIKE '%технология%')
