use UNIVER;

SELECT distinct PULPIT.PULPIT_NAME, FACULTY.FACULTY_NAME
from	FACULTY inner join PULPIT on (FACULTY.FACULTY = PULPIT.FACULTY)
inner join PROFESSION on (PROFESSION.FACULTY = FACULTY.FACULTY)
 where PROFESSION.PROFESSION_NAME LIKE '%технологии%' or PROFESSION.PROFESSION_NAME LIKE '%технология%'
