use UNIVER;

select a.AUDITORIUM, a.AUDITORIUM_TYPE, a.AUDITORIUM_CAPACITY from AUDITORIUM a
where a.AUDITORIUM = (select top (1) aa.AUDITORIUM from AUDITORIUM aa 
where a.AUDITORIUM_TYPE = aa.AUDITORIUM_TYPE
order by aa.AUDITORIUM_CAPACITY desc
)
order by a.AUDITORIUM_CAPACITY desc;