use UNIVER;

SELECT FACULTY.FACULTY, ISNULL( PULPIT.PULPIT, '***') FROM FACULTY LEFT OUTER JOIN PULPIT 
ON FACULTY.FACULTY = PULPIT.FACULTY
WHERE NOT EXISTS (SELECT * FROM PULPIT WHERE PULPIT.FACULTY = FACULTY.FACULTY);
