USE UNIVER;

SELECT TOP 1 (SELECT AVG(PROGRESS.NOTE) FROM PROGRESS WHERE PROGRESS.SUBJECT LIKE 'нюХо') AS нюХо, 
(SELECT AVG(PROGRESS.NOTE) FROM PROGRESS WHERE PROGRESS.SUBJECT LIKE 'ад') AS ад,
(SELECT AVG(PROGRESS.NOTE) FROM PROGRESS WHERE PROGRESS.SUBJECT LIKE 'ясад') AS ясад
FROM PROGRESS

