USE UNIVER;

SELECT P.SUBJECT, P.NOTE, STUDENT.NAME
FROM STUDENT INNER JOIN PROGRESS P ON P.IDSTUDENT = STUDENT.IDSTUDENT
WHERE P.NOTE >=ALL (SELECT PP.NOTE FROM PROGRESS PP WHERE P.SUBJECT = PP.SUBJECT)



--SELECT P.SUBJECT, P.NOTE, STUDENT.NAME
--FROM STUDENT INNER JOIN PROGRESS P ON P.IDSTUDENT = STUDENT.IDSTUDENT
--ORDER BY P.NOTE DESC