USE UNIVER;

SELECT P.SUBJECT, P.NOTE, STUDENT.NAME
FROM PROGRESS P INNER JOIN STUDENT ON STUDENT.IDSTUDENT = P.IDSTUDENT
WHERE P.NOTE >= any (SELECT PROGRESS.NOTE FROM PROGRESS WHERE PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT )


