PRINT 'ROWCOUNT = ' + CAST(@@ROWCOUNT AS VARCHAR(10));
PRINT @@VERSION;
PRINT 'SPID = ' + CAST(@@SPID AS VARCHAR(10));
PRINT @@ERROR;
PRINT @@SERVERNAME;
PRINT 'TRANCOUNT = ' + CAST(@@TRANCOUNT AS VARCHAR(10));
PRINT 'FETCH_STATUS = ' + CAST(@@FETCH_STATUS AS VARCHAR(10));
PRINT 'NESTLEVEL = ' + CAST(@@NESTLEVEL AS VARCHAR(10));
