use UNIVER



SELECT Marks, Count(*) as amount
from (select
CASE
	WHEN PROGRESS.NOTE > 7 THEN 'Отлично'
	WHEN PROGRESS.NOTE > 5 THEN 'Хорошо'
	WHEN PROGRESS.NOTE > 3 THEN 'Удовлетворительно'
	END Marks
FROM PROGRESS
INNER JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
WHERE FACULTY.FACULTY = 'ИДиП') as T
GROUP BY  Marks
ORDER BY 
    CASE Marks
        WHEN 'Отлично' THEN 1
        WHEN 'Хорошо' THEN 2
        WHEN 'Удовлетворительно' THEN 3
    END