use UNIVER

select   GROUPS.PROFESSION, PROGRESS.SUBJECT ,round(avg(cast(PROGRESS.NOTE as float(4))),2) as 'avg'
from GROUPS 
inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE GROUPS.FACULTY = '“Œ¬'
GROUP BY 
 GROUPS.PROFESSION, PROGRESS.SUBJECT

 UNION

 select   GROUPS.PROFESSION, PROGRESS.SUBJECT ,round(avg(cast(PROGRESS.NOTE as float(4))),2) as 'avg'
from GROUPS 
inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE GROUPS.FACULTY = '’“Ë“'
GROUP BY 
 GROUPS.PROFESSION, PROGRESS.SUBJECT